spring:
  datasource:
    url: jdbc:mysql://118.31.53.69:3336/car-sales?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: aCTOl426oJq9VEpvG1sr5ge341nL8PYGUm6
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 118.31.53.69 # Redis服务器地址
    database: 13 # Redis数据库索引（默认为0）
    port: 7500 # Redis服务器连接端口
    password: szgjky@123 # Redis服务器连接密码（默认为空）
    timeout: 30s # 连接超时时间（毫秒）
  data:
    mongodb:
      uri: mongodb://localhost:27017/admin?authSource=admin
#      host: 127.0.0.1
#      port: 27017
#      database: admin
#      username: admin
#      password:
#      authentication-database: admin

minio:
  endpoint: http://118.31.53.69:9050 #MinIO服务所在地址
  bucketName: car #存储桶名称
  accessKey: admin #访问的key
  secretKey: szgjky@123 #访问的秘钥

logging:
  level:
    root: info
    com.jzh.car: debug

logstash:
  host: localhost
  enableInnerLog: false