spring:
  application:
    name: car
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations:
    - classpath*:/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: 8
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

mongo:
  insert:
    sqlEnable: true # 用于控制是否通过数据库数据来插入mongo

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /home/**
      - /product/**
      - /brand/**
      - /alipay/**
      - /portal/sso/login
      - /portal/sso/register
      - /portal/sso/getAuthCode
      - /portal/sso/updatePassword
      - /portal/home/**
      - /portal/product/**
      - /portal/brand/**
      - /portal/member/attention/detail
      - /portal/member/productComment/list
      - /portal/member/readHistory/list
      - /portal/member/SearchHistory/list