spring:
  datasource:
    url: jdbc:mysql://118.31.53.69:3336/car-sales?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: aCTOl426oJq9VEpvG1sr5ge341nL8PYGUm6
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 118.31.53.69 # Redis服务器地址
    database: 13 # Redis数据库索引（默认为0）
    port: 7500 # Redis服务器连接端口
    password: szgjky@123 # Redis服务器连接密码（默认为空）
    timeout: 30s # 连接超时时间（毫秒）
  data:
    mongodb:
      host: 118.31.53.69
      port: 8717
      database: car-port
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: 118.31.53.69:9020
  rabbitmq:
    host: 118.31.53.69
    port: 8672
    virtual-host: /jzo2o
    username: admin
    password: admin@123

minio:
  endpoint: http://118.31.53.69:9050 #MinIO服务所在地址
  bucketName: car #存储桶名称
  accessKey: admin #访问的key
  secretKey: szgjky@123 #访问的秘钥

logging:
  level:
    root: info
    com.jzh.car: debug

logstash:
  host: localhost
  enableInnerLog: false

alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl: